"""initial schema

Revision ID: e3e4239796fd
Revises:
Create Date: 2026-05-28 22:16:23.649564
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'e3e4239796fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_provider_user_id'), ['provider_user_id'], unique=False)

    op.create_table('hubkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=True),
    sa.Column('daily_spend_cap_usd', sa.Float(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hubkey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hubkey_hashed_secret'), ['hashed_secret'], unique=True)
        batch_op.create_index(batch_op.f('ix_hubkey_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hubkey_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hubkey_user_id'), ['user_id'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['hubkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_updated_at'), ['updated_at'], unique=False)

    op.create_table('usagerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['hubkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usagerecord_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usagerecord_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_usagerecord_timestamp'), ['timestamp'], unique=False)

    op.create_table('message',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))

    op.drop_table('message')
    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usagerecord_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usagerecord_model'))
        batch_op.drop_index(batch_op.f('ix_usagerecord_key_id'))

    op.drop_table('usagerecord')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_key_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_created_at'))

    op.drop_table('conversation')
    with op.batch_alter_table('hubkey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hubkey_user_id'))
        batch_op.drop_index(batch_op.f('ix_hubkey_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_hubkey_name'))
        batch_op.drop_index(batch_op.f('ix_hubkey_hashed_secret'))

    op.drop_table('hubkey')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
